name: generate-pages
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Wed 20:00, Thu 00:00/06:00/12:00/18:00 UTC+8
    - cron: '0 12,16,22 * * 2'
    - cron: '0 4,10 * * 3' 
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Prepare
        run: |
          wget https://raw.githubusercontent.com/yhmtsai/kobo-calendar/master/kobo-calendar.py
          wget https://raw.githubusercontent.com/yhmtsai/kobo-calendar/master/README.md -O README.md
          rm -f ics/* 
      - name: Generate
        run: |
          python kobo-calendar.py
          rm kobo-calendar.py
      - name: Upload
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          if [[ `git status --porcelain` ]]; then
            git add --all
            git commit -m "generate gh-pages"
            git push
          else
            echo "no changes"
          fi
